name: Deploy to Kubernetes

on:
  push:
    branches:
      - master
      - stg

env:
  DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/myself
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  build:
    runs-on: jylab-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, tag, and push
        run: |
          if [ $BRANCH_NAME == 'master' ]; then
            branchTag=prd
          else
            branchTag=$BRANCH_NAME
          fi
          dateTag=$branchTag-$(date +'%Y%m%d')

          docker build -t $DOCKER_REPO:$dateTag -t $DOCKER_REPO:$branchTag .
          docker push $DOCKER_REPO:$dateTag
          docker push $DOCKER_REPO:$branchTag

